[project]
name = "crawl4ai-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.6.3",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.3",
]
